# Rutas de las páginas estáticas del sitio
ayuda:
    pattern:  /ayuda/
    defaults: { template: '::estaticas/ayuda.html.twig' }

privacidad:
    pattern:  /privacidad/
    defaults: { template: '::estaticas/privacidad.html.twig' }

sobre_nosotros:
    pattern:  /sobre-nosotros/
    defaults: { template: '::estaticas/sobre-nosotros.html.twig' }