usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

# Ruta simple de la portada con redireccion
_portada:
    path:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }

# Ruta completa de la portada (con el slug de la ciudad)
portada:
    path:  /{ciudad}/
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: %cupon.ciudad_por_defecto% }

pagina_estatica:
    path:     /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }

#_paginas_estaticas:
#    resource: routing_paginas.yml
#    prefix: /sitio
#    defaults: { _controller: FrameworkBundle:Template:template }