# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:

        # Usuarios del frontend
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: email }

        in_memory:
            memory: ~

    firewalls:

        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                remember_me: true
            logout:
                path: usuario_logout

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:

        - { path: ^/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    encoders:

        # el coste del algoritmo se ha reducido a 8 para que la carga de los datos
        # de prueba no sea demasiado lenta (se generan cientos de usuarios). En
        # una aplicación real, es mejor no cambiar el valor por defecto (que es 12)
        AppBundle\Entity\Usuario: plaintext

    role_hierarchy:

        ROLE_ADMIN: ROLE_USUARIO