# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:

        # Usuarios del frontend
        usuarios:
            entity: { class: AppBundle\Entity\Usuario, property: email }

        tiendas:
            entity: { class: AppBundle\Entity\Tienda, property: login }

        in_memory:
            memory: ~

    firewalls:

        # Firewall utilizado en la parte de gestion para tiendas o extranet
        extranet:
            pattern: ^/extranet
            provider: tiendas
            anonymous: ~
            form_login:
                login_path: /extranet/login
                check_path: /extranet/login_check
            logout:
                path: extranet_logout

        # Firewall global utilizado en la parte pública o frontend
        frontend:
            pattern:        ^/*
            anonymous:      ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                remember_me: true
            logout:
                path: usuario_logout

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(es|en)/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLE_TIENDA }

    encoders:

        # el coste del algoritmo se ha reducido a 4 para que la carga de los datos
        # de prueba no sea demasiado lenta (se generan cientos de usuarios). En
        # una aplicación real, es mejor no cambiar el valor por defecto (que es 12)
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4

        AppBundle\Entity\Tienda:
            algorithm: bcrypt
            cost: 4

    role_hierarchy:

        ROLE_ADMIN: ROLE_USUARIO