# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.text:
            class: Twig_Extension_Debug
            tags:
                - { name: twig.extension }

    app.login_listener:
            class: AppBundle\Listener\LoginListener
            arguments: ['@router']
            tags:
                - { name: kernel.event_listener, event: security.interactive_login }
                - { name: kernel.event_listener, event: kernel.response }

    app.twig.cupon_extension:
            class: AppBundle\Twig\Extension\CuponExtension
            tags:
                - { name: twig.extension }

    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }